version: 2
jobs:
  run_tests:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install npm dependencies
          command: |
            npm update
            npm install --save --no-package-lock
      - run:
          name: Run Unit Tests
          command: |
            echo $GOOGLE_CLOUD_KEYS
            echo $HOME
      - store_test_results:
          path: test-results
          
workflows:
  version: 2
  one_and_two: # this is the name of our workflow
    jobs: # and here we list the jobs we are going to run.
      - run_tests       
